@MyStore.Api_HostAddress = https://localhost:7157
@userToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InNoaW1vbkRhaGFuIiwic3ViIjoic2hpbW9uRGFoYW4iLCJqdGkiOiJiNmFmMjg2YiIsInZhbGlkRm9yTGF0ZXMiOiIzIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTA4MSIsImh0dHBzOi8vbG9jYWxob3N0OjcxNTciXSwibmJmIjoxNzUzNjAzNjQ5LCJleHAiOjE3NjE1NTI0NDksImlhdCI6MTc1MzYwMzY1MCwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.nzbdJRUaPj9Xwcolb1HUYJpxE5F8vlt9W9fDWQXVUSc
### GET BY ID

GET {{MyStore.Api_HostAddress}}/products/4
accept: application/json
Content-Type: application/json


### Add New Product
POST {{MyStore.Api_HostAddress}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlNoaW1vIiwic3ViIjoiU2hpbW8iLCJqdGkiOiJkNjgwOTZjNiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwODEiLCJodHRwczovL2xvY2FsaG9zdDo3MTU3Il0sIm5iZiI6MTc1MzYwODI2MywiZXhwIjoxNzYxNTU3MDYzLCJpYXQiOjE3NTM2MDgyNjUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.pUxSf3rXM1j1FMTC468678EYBT--nedcqE5fSMzoF0A



{
  "productName": "PRODUCT NO 8821",
  "productPrice": 80,
  "description": "abcAAA"
}

### Get All Products
GET {{MyStore.Api_HostAddress}}/products
Content-Type: application/json


### UPDATE product by ID
PUT {{MyStore.Api_HostAddress}}/products/1 // full update
Content-Type: application/json


{
    "id": 1,
    "name": "Sample Product CHANGED",
    "price": 200,
    "description": "A sample product description. CHANGED"
}

####

DELETE {{MyStore.Api_HostAddress}}/products/1

####

# PATCH {{MyStore.Api_HostAddress}}/products/1 // partial update
# Content-Type: application/json

# {
#   "price": 12.6
# }