@MyStore.Api_HostAddress = http://localhost:1658
@userToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlNoaW1vIiwic3ViIjoiU2hpbW8iLCJqdGkiOiJkNjgwOTZjNiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwODEiLCJodHRwczovL2xvY2FsaG9zdDo3MTU3Il0sIm5iZiI6MTc1MzYwODI2MywiZXhwIjoxNzYxNTU3MDYzLCJpYXQiOjE3NTM2MDgyNjUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.pUxSf3rXM1j1FMTC468678EYBT--nedcqE5fSMzoF0A
@adminToke = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InNoaW1vbkFkbWluIiwic3ViIjoic2hpbW9uQWRtaW4iLCJqdGkiOiJmNzIzMTNjNiIsInJvbGUiOiJBZG1pbiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjUwODEiLCJodHRwczovL2xvY2FsaG9zdDo3MTU3Il0sIm5iZiI6MTc1MzYxNTY5MSwiZXhwIjoxNzYxNTY0NDkxLCJpYXQiOjE3NTM2MTU2OTUsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.cOZx8A9SGkoiLgk8arUx2WeeRBN1R-ZGKBlspgy0S7A
### GET BY ID

GET {{MyStore.Api_HostAddress}}/products/2
accept: application/json
Content-Type: application/json


### Add New Product
POST {{MyStore.Api_HostAddress}}/products
Content-Type: application/json
Authorization: {{userToken}}



{
  "productName": "Bamba",
  "productPrice": 10,
  "description": "Shel osem"
}

### Get All Products
GET {{MyStore.Api_HostAddress}}/products
Content-Type: application/json


### UPDATE product by ID
PUT {{MyStore.Api_HostAddress}}/products/1 // full update
Content-Type: application/json
Authorization: {{userToken}}

{
    "id": 1,
    "name": "Bamba 123123",
    "price": 14.16,
    "description": "Bamba nugat shel OSEM"
}

####

DELETE {{MyStore.Api_HostAddress}}/products/5
Authorization: {{adminToke}}

### SEQ LOGGING DOCKER COMMAND:
##docker run -d --name seq -e ACCEPT_EULA=Y -v seq_data:/data -p 5341:80 -p 5342:443 datalust/seq:latest
####

# PATCH {{MyStore.Api_HostAddress}}/products/1 // partial update
# Content-Type: application/json

# {
#   "price": 12.6
# }