@MyStore.Api_HostAddress = http://localhost:5081

### GET BY ID

GET {{MyStore.Api_HostAddress}}/products/1
accept: application/json
Content-Type: application/json


### Add New Product
POST {{MyStore.Api_HostAddress}}/products
Content-Type: application/json

{
  "name": "This is the new Product2",
  "price": 46,
  "description": "aasdasdas"
}

### Get All Products
GET {{MyStore.Api_HostAddress}}/products
Content-Type: application/json


### UPDATE product by ID
PUT {{MyStore.Api_HostAddress}}/products/1 // full update
Content-Type: application/json


{
    "id": 1,
    "name": "Sample Product CHANGED",
    "price": 200,
    "description": "A sample product description. CHANGED"
}

####

DELETE {{MyStore.Api_HostAddress}}/products/1

####

# PATCH {{MyStore.Api_HostAddress}}/products/1 // partial update
# Content-Type: application/json

# {
#   "price": 12.6
# }