@MyStore.Api_HostAddress = http://localhost:5081

### Add New Product
POST {{MyStore.Api_HostAddress}}/products
Content-Type: application/json

{
  "name": "Sample Product",
  "price": 19.99,
  "description": "A sample product description."
}

### Get All Products
GET {{MyStore.Api_HostAddress}}/products
Content-Type: application/json


